### ISSUE TITLE
sfc.getDelegation return 0 for all timestamps

### ISSUE THREAD

**Issue by Chunam** [Fantom-foundation/go-opera#102]
**Describe the bug**
the SFC method getDelegation does not return correct timestamps since update to opera.

**To Reproduce**
1. opera attach, then execute :
>sfc.getDelegation('0x467af86ba64afc01ea769065cb4763c01d810848', 30)
return : 
{
  address: "0x467af86ba64afc01ea769065cb4763c01d810848",
  amount: 4690000000000000000,
  createdEpoch: 0,
  createdTime: 0,
  deactivatedEpoch: 0,
  deactivatedTime: 0,
  toStakerID: 30
}

**Expected behavior**
createdTime should have the correct timestamp

**Comment by uprendis** [comment]
Hello @Chunam,
Good day to you!

Since the upgrade to SFCv3, creation timestamp/epoch and deactivation timestamp/epoch aren't a part of the delegation anymore. We preserved them in the API output only to avoid a failure of clients which might read them

The `sfc` API namespace is deprecated - it will be removed in one of future updates. Please consider retriving data about delegations and validators from the SFCv3 contract (either from its methods, or by parsing its logs): https://github.com/Fantom-foundation/opera-sfc/blob/main/contracts/sfc/SFC.sol
