### ISSUE TITLE
Fast node syncing or pruning

### ISSUE THREAD

**Issue by soltrac** [Fantom-foundation/go-opera#128]
Hi,

Is there any plan to add pruning or fast node syncing like original geth? Right now we can only make a full node sync that is very slow and uses lots of ssd space.

**Comment by uprendis** [comment]
Hello @soltrac ,
Good day to you!
As far as I can tell, we'll have a similar feature eventually. That would be a little bit more involved to implement due to the nuances of aBFT
At the moment, we've ported the EVM snapshots support from geth 1.10.3 (PR #126), which will allow to prune unused EVM trie nodes with `opera snapshot prune-state` command. Separately, we're also working on making this trie pruning process automatic (just like geth does it by default)

**Comment by soltrac** [comment]
Awesome!!!! I will close this and will wait. Meanwhile. I will prune offline like geth does.
