### ISSUE TITLE
Cannot open database

### ISSUE THREAD

**Issue by soltrac** [Fantom-foundation/go-opera#145]
My system crashed. When I try to open opera again, I receive this message.

Fatal: Failed to make engine: failed to open existing databases: dirty state: gossip-23111: DE001695004CFEBA6D8516950050E46F8622

Is it possible to try to fix it? Or must I start from zero again?

Thanks in advance

**Comment by uprendis** [comment]
Hello @soltrac,
Good day to you!

There's no way to fix that, you'll have to erase chain data and start from scratch:
```
rm -r ~/.opera/chaindata
opera --your-favourite-flags
```

Similarly to `bitcoind`, go-opera flushes data only periodically. If it had crashed between data flushes, you would safely start from a latest flushed data set. But since it has crashed during a flush, it's in a middle of an inconsistent state now

**Comment by soltrac** [comment]
Thanks for the info then.
