### ISSUE TITLE
transactions in one block is not sorted by gas price

### ISSUE THREAD

**Issue by DebugFuture** [Fantom-foundation/go-opera#161]
Hello, I find transactions in one block sometimes are not sorted by gas price. Is it by design or a bug? 

for example, transactions in this block:
https://ftmscan.com/txs?block=15986863

**Comment by uprendis** [comment]
Hello @DebugFuture,
Good day to you!
Yeah, it's by design
Unlike Ethereum, blocks in validators aren't created by a single participant but rather deduced from a collective effort of the validators group. This process is also asynchronous, meaning that at a point of transaction origination, validator has no idea what a block containing this transaction will look like. As a result, block may contain transactions from multiple validators, where each validator sorted his transactions by gas price, but combining transactions from multiple validators, the transactions aren't necessarily sorted by gas price anymore

**Comment by DebugFuture** [comment]
thank you for the explanation.

**Comment by DebugFuture** [comment]
thank you for the explanation.
