### ISSUE TITLE
Any pruned go-opera data snapshots for speeding up sync?

### ISSUE THREAD

**Issue by barryz** [Fantom-foundation/go-opera#164]
Block sync from scratch is very slow, I wonder that official has any pruned go-opera data snapshots for speeding up sync?

**Comment by uprendis** [comment]
Hello @barryz ,
Good day to you!
Currently there's no such datadir snapshots, because an "official" data source wouldn't be trustless. That is a reason why consensus algorithms exist - to be able to calculate consensus on a latest state in a decentralized way
Currently we're working on implementing an additional consensus mechanism which will allow to sync up to a certain point in history without re-applying the transactions before that point

**Comment by Timofeyeff** [comment]
Hi @quan8! I want to dowloaded snapshot from https://download.fantom.network/opera_pruned_19nov21.tgz, but download speed only 50 kb/s, and ETA is 40 days. Were i may downlod snapshot with normal speed.
Regards, Maksim
