### ISSUE TITLE
Incoming event rejected

### ISSUE THREAD

**Issue by soltrac** [Fantom-foundation/go-opera#167]
**Describe the bug**
Since today, I'm receiving this message on my node

WARN [09-20|07:38:10.095] Incoming event rejected                  event=36378:1:613a6c creator=57 err="wrong event epoch hash"
WARN [09-20|07:38:10.096] Incoming event rejected                  event=36378:1:a29ace creator=54 err="wrong event epoch hash"
WARN [09-20|07:38:26.017] Incoming event rejected                  event=36378:1:01c642 creator=50 err="wrong event epoch hash"
WARN [09-20|07:38:26.018] Incoming event rejected                  event=36378:1:0f51f8 creator=56 err="wrong event epoch hash"
WARN [09-20|07:38:26.018] Incoming event rejected                  event=36378:1:1bf11d creator=55 err="wrong event epoch hash"
WARN [09-20|07:38:26.018] Incoming event rejected                  event=36378:1:55ba5d creator=59 err="wrong event epoch hash"
...... etc, all the time

And the node is doing nothing. What is happening?

**Comment by uprendis** [comment]
Hello @soltrac,
Good day to you!
The node has computed its state differently to other nodes - either due to an outdated version or an `opera` bug or a hardware-related failure. It is unable to continue syncing, you will have to upgrade to a latest `opera` version (currently `1.0.2-rc.5`) and resync the blockchain (erase `~/.opera/chaindata`).
- What version of `opera` did you use?
- Did you use this node as an API node?

**Comment by quan8** [comment]
It could be some issue with the connection or the machine and the db was not in the good state. Please resync your node. For further support, please contact our support team on Discord or TG.
