### ISSUE TITLE
Running in light mode

### ISSUE THREAD

**Issue by 0xrin1** [Fantom-foundation/go-opera#221]
**Is your feature request related to a problem? Please describe.**
Trying to run in light mode but the flag is not available

**Describe the solution you'd like**
A way of running a go-opera light node

**Describe alternatives you've considered**
Just running a normal node

**Additional context**
Would be nicer not to have to sync the entire chain

**Comment by hkalina** [comment]
Running live-pruned node is supported in 1.1.1-rc2 - use:
* `--syncmode=snap` to initialize the EVM state database directly to the current chain state (instead of running all chain blocks)
* `--gcmode=light` to enable live-pruning - to remove EVM data immediately when they become historical
* Use not-full genesis file - for example [mainnet-109331-no-history.g](https://download.fantom.network/mainnet-109331-no-history.g)

For example:
```
opera --datadir=./data  --syncmode=snap --gcmode=light --genesis=mainnet-109331-no-history.g
```

**Comment by buzzkillb** [comment]
Confirming the 2 flags above work for RPC, about 20 hours for me to sync. Using about 714 GB space. Trying branch 1.1.2-rc2
