### ISSUE TITLE
import evm history ?

### ISSUE THREAD

**Issue by masayil** [Fantom-foundation/go-opera#240]
I use `/root/svc/opera --genesis /root/svc/mainnet.g --nousb --http --http.addr '0.0.0.0' --http.port 8545 --http.corsdomain "*" --http.vhosts "*" --ws --ws.addr '0.0.0.0' --ws.port 8546  --ws.origins '0.0.0.0' --graphql --graphql.corsdomain '*' --graphql.vhosts '*' --datadir "/root/svc/node" --http.api "net,eth,web3" --ws.api "net,eth,web3"` to run an archive node. 
Should I import evm history?
![image](https://user-images.githubusercontent.com/65291464/152913215-d1883044-17d1-4cee-9ac0-078f3277424f.png)

**Comment by uprendis** [comment]
Yes, you need to do so for an archive node

**Comment by masayil** [comment]
> Yes, you need to do so for an archive node

Do it after the node finish syncing ?

**Comment by uprendis** [comment]
You should stop the node before `import evm` and `check evm`
You can do it before or after syncing, it will not make a difference, except that `check evm` will take much longer if done after syncing (since it'll check much more data). You can skip the `check evm` command in a case you trust that the downloaded file is correct
