### ISSUE TITLE
The method eth_feeHistory does not exist/is not available

### ISSUE THREAD

**Issue by peak3d** [Fantom-foundation/go-opera#249]
**Describe the bug**
When connecting MetaMask to v1.1.0-rc.2 node, the console get filled with lot of:

`WARN [02-09|20:31:08.871] Served eth_feeHistory                    conn=127.0.0.1:43074 reqid=2497188688232592 t="28.632µs"  err="the method eth_feeHistory does not exist/is not available"` messages.

**To Reproduce**
1. Launch node with http switch set and net module configured
2. Connect with MetaMask

I'm testing with : HTTPModules = ["eth", "ftm", "dag", "abft", "web3", "net"]

I want to dig into it by myself just for exercise, to speed up things it would be nice and helpful if you can point me into the right direction to solve this (I assume in fantom's go-ethereum). Appreciate every hint!

- peak3d

**Comment by hadv** [comment]
@peak3d I think we need to add `feeHistory()` method in to the ftm public api here

https://github.com/Fantom-foundation/go-opera/blob/master/ethapi/api.go#L529

**Comment by hadv** [comment]
@peak3d I think that we need to implement the `FeeHistory()` method for `EthAPIBackend` in https://github.com/Fantom-foundation/go-opera/blob/bff25c0c4fe164d3f8301573f9236eaf0efcc2ef/gossip/ethapi_backend.go#L37

**Comment by uprendis** [comment]
Unfortunately we don't have this method yet, because gas market is slightly different than in Ethereum due the the DAG aBFT algorithm. In a case you need `eth_feeHistory` for fee estimation, then you have to use `eth_gasPrice` or `eth_maxPriorityFeePerGas` instead. Moreover, those oracles are enforced. If you use a much lower value, then tx will get pruned with "transaction underpriced". In a case you need a reduced chance of transaction getting pruned, you may multiply the oracle output by `1.2`. And vice versa, you may try to multiply it by ~0.8 if you're okay with a higher chance of transaction getting pruned (or taking longer to confirm)

**Comment by peak3d** [comment]
Thanx much for the advise @hadv, @uprendis ! For now it's only a personal hackaton, if I finally lead to something useable I'll provide via PR!
