### ISSUE TITLE
Genesis file?

### ISSUE THREAD

**Issue by lonnietc** [Fantom-foundation/go-opera#294]
I was able to download and compile Opera on my Ubuntu 20.04 system but to run it, I need an initial genesis file that I cannot locate in the repository.

I want to set up a private testnet network to experiment and develop.

Can you please provide the genesis file?
thanks

**Comment by proteanx** [comment]
The genesis file either needs to be generated from lachesis or you can download it here: https://opera.fantom.network/mainnet.g

**Comment by lonnietc** [comment]
Is that correct in that I see the mainnet.g to be 1 GB in size? That is a HUGE file for a configuration.

What is the documentation to generate it via lachesis?

Also, in my reading I see that there is also a way to have a much smaller configuration yml file

Thanks again

**Comment by uprendis** [comment]
Hello @lonnietc,
Good day to you!
It's not a configuration at all (configuration is set via config.toml or flags). It's genesis state of the network. It's large because it starts not from the very start of network (which is in 2019) but from 2021. Chronologically, we had go-lachesis client first, then we migrated to go-opera client. The new network has started from last state of the previous network, which is reflected in this genesis file. You can download the go-lachesis client (1.0.0-rc.0) to sync up the go-lachesis history and automatically generate the genesis file for go-opera, but it would be much simpler to download the resulting file from the server

**Comment by lonnietc** [comment]
Hello @uprendis 

Thanks for the clarification on the genesis and it makes sense now why it is larger.

I there a command line switch on Opera to generate fresh Genesis or base config.toml file set up that I can perform to establish a small private TestNet which nothing in the blockchain and then fire up some different physical nodes to test out an play with to get a feel for things?

That would probably be a better beginning point for me although I have just downloaded the mainnet.g file as well.

Thanks again and have a good day

**Comment by lonnietc** [comment]
@quan8 

Why was this closed so quickly when we were in the middle of a conversation in which I was asking about what command line switches were needed for Opera in order to generate a new Genesis and configuration for use in a small Testnet?

**Comment by uprendis** [comment]
Currently there's no direct tool for that unfortunately, but stay tuned - it may change in near future, especially after #271
For testing purposes, it may be enough to use fakenet: https://github.com/Fantom-foundation/lachesis_launch/blob/master/docs/launch-private-network.md
