### ISSUE TITLE
Metric Collection failed

### ISSUE THREAD

**Issue by deepakjuit** [Fantom-foundation/go-opera#371]
`Oct 03 09:40:14 ip-10-0-136-81 opera[13473]: ERROR[10-03|09:40:14.635] Metrics collection failed                database=epochs err="bad syntax of ioStats "

Oct 03 09:40:14 ip-10-0-136-81 opera[13473]: ERROR[10-03|09:40:14.640] Bad syntax of ioStats                    database=epochs ioStats=

Oct 03 09:40:14 ip-10-0-136-81 opera[13473]: ERROR[10-03|09:40:14.640] Metrics collection failed                database=epochs err="bad syntax of ioStats "

Oct 03 09:40:14 ip-10-0-136-81 opera[13473]: ERROR[10-03|09:40:14.640] Bad syntax of ioStats                    database=epochs ioStats=
`

**Comment by hadv** [comment]
Hi @deepakjuit 

Due to the epochs database didn't have the iostats metrics then it report the error log but the metric collection for all other dbs and other metrics are still be successful.

By the way, we can improvement for leveldb metric collection in this PR https://github.com/Fantom-foundation/go-ethereum/pull/41

**Comment by quan8** [comment]
Hi @deepakjuit , does it work with our latest releases?
