### ISSUE TITLE
Method handler crashed - trace_transaction

### ISSUE THREAD

**Issue by yaanakbr** [Fantom-foundation/go-opera#487]
**Describe the bug**
I have a problem with a certain transaction when using Fantom trace_transaction endpoint for this transaction: https://ftmscan.com/tx/0x72a110b0a48c45c8fbd300b212878a9bec0056db9f1498ce70b5f0ccef3377ed

I get this error message "method handler crashed"

**To Reproduce**

```
{
  "method": "trace_transaction",
  "params": [
    "0x72a110b0a48c45c8fbd300b212878a9bec0056db9f1498ce70b5f0ccef3377ed"
  ],
  "id": 1,
  "jsonrpc": "2.0"
}
```

**Expected behavior**

Return the trace transaction, we think this is an issues with the new go-opera version.

**Screenshots**

<img width="1119" alt="SCR-20230706-kecu" src="https://github.com/Fantom-foundation/go-opera/assets/126090886/2fad997f-5b3f-41c7-8a7c-191057c2f40e">

**Desktop (please complete the following information):**
 - OS: 13.0 (22A8380)
 - Browser chrome
 - Version opera_release: release/txtracing/1.1.2-rc.6

**Comment by yaanakbr** [comment]
Hey guys! I just wanted to bump this again :)

**Comment by jenikd** [comment]
Hi @yaanakbr, problem is, that this transaction is one of the hard fork transactions which occured forking from lachesis to opera. It is done from zero address and that is failing in the transaction replay mechanism because of the signer.
I'll look at this and prepare a fix for this. Thanks for reporting this issue.

**Comment by quan8** [comment]
Hi @yaanakbr , can you double check this issue with version 1.1.3-rc.5?
