### ISSUE TITLE
Reliable way to time emission

### ISSUE THREAD

**Issue by fetsorn** [Fantom-foundation/go-opera#91]
**Describe the bug**
My team struggles to time token emission on Fantom. 
Our emission policy is to issue tokens steadily every day so that the total supply reaches N after a year. The formula takes in current time to calculate emission. 
We tried to rely on average block time but it has been very volatile and the emission quickly got out of schedule.
This is not an issue on other blockchains. We're commited to use Fantom. 

How do we best reference time on ftm? Is there/will there be constant block time? What guarantees are provided for timestamps, perhaps they are more reliable than on other chains? 

**To Reproduce**
https://ftmscan.com/chart/blocktime
https://ftmscan.com/chart/tx

**Expected behavior**
Other chains provide steady blocktime.
https://etherscan.io/chart/blocktime
https://bscscan.com/chart/blocktime

**Comment by uprendis** [comment]
Hello @fetsorn,
Good day to you!

Timespan between blocks isn't controlled in Opera. Normally, it can be anywhere in a range of (0, 30 minutes). Processing of new blocks depends on events emission by validators. Each validator will time its emission depending on many factor, the main of which is whether or not there there's some transactions to originate or confirm

I wouldn't recommend making tokens emission dependent on a number of passed blocks. Instead, you can make it dependent on a direct difference between block timestamps. You can obtain current block time with `block.timestamp` or `now` in Solidity.

In Ethereum and some other blockchains, it wouldn't be correct to do so because block timestamp may be biased by a miner.
In Opera, it is a secure way to implement such logic

Here're are some properties of Opera block timestamps which you might need to know for your contract:
- can be biased only if at least 1/2W of validators collude about a shift of time
- block timestamp of future blocks is never smaller than a block timestamp of a previous block. That is, if `block A` < `block B`, then `block A timestamp` <= `block B timestamp`
- block timestamp normally doesn't point to future, it points to a recent past. If there were no blocks for for a long time, it may point to a relatively distant past - up to ~30 minutes in the past

If you're curious how block timestamps work in Opera:
> In more detail, block timestamp in Opera is weighted median timestamp of Atropos, l little bit more information on which may be found there: https://github.com/Fantom-foundation/go-opera/wiki/Event , see `MedianTime`

**Comment by fetsorn** [comment]
@uprendis Thanks a lot for the timely response and lots of info, will use timestamps then.
