### ISSUE TITLE
Where to find the genesis file?

### ISSUE THREAD

**Issue by Sleapy31** [Fantom-foundation/go-opera#92]
Hi. Sorry if the question is a bit stupid but where can I find genesis files ? Or how can I generate it ?

**Comment by mtyou** [comment]
i also have same question, @Sleapy31 have you get it ?

**Comment by uprendis** [comment]
Currently there's only a genesis file for the Opera public testnet downloadable at https://opera.fantom.network/testnet.g, genesis hash is 0xc4a5fc96e575a16a9a0c7349d44dc4d0f602a54e0a8543360c2fee4c3937b49e
Check out instructions on how to join Opera testnet: https://github.com/Fantom-foundation/lachesis_launch/tree/release/opera-v1.0.0-rc1
Mainnet hasn't migrated to go-opera yet, you would need to use go-lachesis client to join the Opera mainnet: https://github.com/Fantom-foundation/lachesis_launch/blob/c1a6b668e8d1f9cc4558e2899d84fad89815fd91/scripts/readonly-lachesis-1.0.0-rc0.sh 
Use version `release/1.0.0-rc.0`, it will automatically switch to go-opera mode after the migration, so that wouldn't need to upgrade to `go-opera` manually
If you were looking to generate a new genesis file: https://github.com/Fantom-foundation/lachesis_launch/blob/release/opera-v1.0.0-rc1/docs/launch-private-network.md

**Comment by quan8** [comment]
" where can I find genesis":
1. If your node was migrated successfully. The generated genesis file is located at:
~/.lachesis/opera/genesis.g
2. Or you can download it at:
wget https://opera.fantom.network/mainnet.g

See guide for more info:
https://github.com/Fantom-foundation/lachesis_launch/blob/release/opera-v1.0.0-rc1

**Comment by doublesharp** [comment]
@quan8 is the genesis file required every time you start opera?

**Comment by quan8** [comment]
@doublesharp  yes

**Comment by doublesharp** [comment]
@quan8 thanks, is it normal for it to take a while to decode/apply the genesis file? is there a way to speed up the (re)startup time?
