### ISSUE TITLE
Transaction processing is too slow

### ISSUE THREAD

**Issue by Ten-Ou** [Fantom-foundation/go-opera#94]
server :Ubuntu 18.04 LTS
CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
RAM：16G

[Opera.Emitter]
VersionToPublish = "1.0.0-rc.0"

I used fakenet to build 3 nodes to execute transactions. The number of transactions in txpool is very slow. How can I improve the processing speed of pending transactions in txpool?

**Comment by uprendis** [comment]
Hello Ten-Ou,
Good day to you!

Is your setup related to the issue #93, where all the transactions are sent from a single address?
If yes, then there's 2 things which you can use:
- Send the transactions from multiple addresses. Due to the consensus being asynchronous and leaderless, there's a couple of trade-offs related to it. While your setup will process about 125 transactions per second overage (by default), capacity for an individual account is limited to ~10 transactions per second
- Since you're working in the local fakenet, you can bend many setting to your will. You can set the config to:
```
[Opera.Emitter]
MaxTxsPerAddress = 32
```
Increasing MaxTxsPerAddress to more than 32 will not have an effect, as all transactions are divided into chunks of 32 by their nonce, and each chunk will be attributed to different validators

If you're already sending transactions from multiple addresses and you need more than ~130 transactions per second, then, in fakenet, validator 1 also has the authority to change network constants via the pre-deployed NodeDriver contract, including the ones related to the network capacity constraints. Let me know if it's what you're looking for

**Comment by Ten-Ou** [comment]
Hello uprendis,
Good day to you!

I already use multiple addresses to send transactions. And modified the MaxTxsPerAddress in the configuration file to 100, but the transaction processing speed is still not ideal. It feels that the parameter has been modified, but it does not take effect.
There is one more I want to ask. When the gas usage of each transaction is high, the number of packaged transactions of the block decreases. I tried to modify the parameter value of [Lachesis.Net.Economy.ShortGasPower], but the last one was tested The result is not valid. The following is my modified configuration parameter data:
[Lachesis.Net.Economy.ShortGasPower]
InitialAllocPerSec = 140000000
MaxAllocPerSec = 1400000000
MinAllocPerSec = 1400000
MaxAllocPeriod = 600000000000
StartupAllocPeriod = 10000000000
MinStartupGas = 560000

[Lachesis.Net.Economy.LongGasPower]
InitialAllocPerSec = 28000000
MaxAllocPerSec = 280000000
MinAllocPerSec = 2800000
MaxAllocPeriod = 36000000000000
StartupAllocPeriod = 50000000000
MinStartupGas = 560000|

Thank you very much for your answers.

**Comment by quan8** [comment]
@Ten-Ou  Thanks for your interests. Answer was given. We have further improvements in later releases.
